### ISSUE TITLE
Tilde notation to reference user's home dir does not work in ClusterConfig.Spec.Hosts[0].SSHKeyPath

### ISSUE THREAD

**Issue by slystopad** [Mirantis/launchpad_legacy#10]
`launchpad-linux-x64 apply` fails to find SSH key file if the path contains `~` to reference users's home directory (like in example [2]).
The tool fails to find the key file but the error message [0] in this case is obscure (worth to return obvious message). OS is [1]

[0]
```
FATA[0002] Key: 'ClusterConfig.Spec.Hosts[0].SSHKeyPath' Error:Field validation for 'SSHKeyPath' failed on the 'file' tag
Key: 'ClusterConfig.Spec.Hosts[1].SSHKeyPath' Error:Field validation for 'SSHKeyPath' failed on the 'file' tag 
```
[1]
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
[2] https://github.com/Mirantis/launchpad/blame/master/docs/configuration-file.md#L19

**Comment by jnummelin** [comment]
This is fixed now in 0.10+ releases
