### ISSUE TITLE
Version on DL is not showing 1.0

### ISSUE THREAD

**Issue by ruizmarlon** [Mirantis/launchpad_legacy#17]
Official download version(s) not showing 1.0

is the following expected?

Checked mac & linux DLs
```
$ launchpad version
version: 0.11.3
commit: 4056b8e
```

**Comment by nevalla** [comment]
Yes, it's expected. `0.11.3` is the latest Launchpad version at this moment: https://github.com/Mirantis/launchpad/releases

**Comment by ruizmarlon** [comment]
The getting-started.md shows the following which may be misleading for users:

```
$ launchpad version
version: 1.0.0
```

**Comment by kke** [comment]
1.0 released, so this is fixed :)
