### ISSUE TITLE
upgrade example: docs/upgrades.md

### ISSUE THREAD

**Issue by ruizmarlon** [Mirantis/launchpad_legacy#20]
In the example the upgrade verbiage and yaml reference a docker engine that isn't released.

This maybe confusing to users.  Currently there is only one docker engine compatible(`19.03.8`) with `UCP 3.3.0`.
```
Say you want to upgrade the Docker EE engine running in the cluster. You've bootsrapped the cluster with version `19.03.8` and want to upgrade to say `19.03.14`.
```
yaml:

```
  engine:
    version: 19.03.14 # was previously 19.03.8
```

**Comment by kke** [comment]
Documentation has moved to https://docs.mirantis.com/containers/v3.1/dockeree-products/deployment-tools/launchpad.html
