### ISSUE TITLE
/etc/environment not updated before pkg install

### ISSUE THREAD

**Issue by 53d117460ec63d70** [Mirantis/launchpad_legacy#48]
```/etc/environment``` gets updated with ```environment``` values from ```launchpad.yaml``` after required OS packages are installed rather than before. If it was updated before OS package installations we could set HTTP proxy settings once in the ```launchpad.yaml``` rather that having to set on each target host before we run ```launchpad apply```.

**Comment by kke** [comment]
On the 1.0.0-rc1 you could use the before/after-hooks to work around that, but I think this is something that needs to be addressed.

**Comment by kke** [comment]
It's an easy fix, probably going to make it into 1.0 which should be released shortly.
