### ISSUE TITLE
Ability to pass launchpad config using stdin

### ISSUE THREAD

**Issue by surskitt** [Mirantis/launchpad_legacy#56]
It would be very useful to be able to pass the launchpad yaml config into the command through standard in, for example when taking input from a computed source like terraform outputs. Instead of having to write to file, we could do something like below:

    terraform output launchpad_yaml | launchpad apply -c -

**Comment by kke** [comment]
Yep, I've been thinking about this too. Now that the terraform examples output yaml it makes even more sense. I've made the change and this will be available in version 1.1.
