### ISSUE TITLE
Macro is not triggered always for the first time

### ISSUE THREAD

**Issue by Ruxter** [Mirantis/launchpad_legacy#64]
Hi!
I am using your soft and it's very cool!
But I am facing some little issue :(
I am using Launchpad X as stream deck while streaming for scene switching etc.
Anyway it seems sometimes it needs 2-3 taps for triggering the macro.
I set it like this:
![obrazek](https://user-images.githubusercontent.com/23618321/109061664-3a25a280-76e7-11eb-9559-eb33977ba4cd.png)

Am I doing something wrong or it's "feature" or can I evade it somehow?
Thanks for help!

**Comment by Ruxter** [comment]
EDIT: Seems this happens when ctrl/alt is added to the macro

**Comment by kke** [comment]
Seems you are using some other software.
