### ISSUE TITLE
terraform 'map' function has been deprecated and replaced with 'tomap' function.

### ISSUE THREAD

**Issue by jas-atwal** [Mirantis/launchpad_legacy#77]
The 'map' function has been deprecated and replaced with 'tomap' function.  All terraform files that contain this function should be updated to reflect this and also so that the examples terraform files work out of the box.

https://www.terraform.io/docs/language/functions/tomap.html

With the current examples you will not be able to continue with the deployment of infra. on AWS for example until such a change is made.

**Comment by stevejr** [comment]
@jas-atwal - PR #78 has been raised. If you need to fix this ASAP for a customer then please look at the changes and replicate
